TencentBlueKing/bk-user

- src/bkuser_global/drf_crown/crown.py
- src/saas/bkuser_shell/config_center/views.py
> fix last request data remain when pass in serializer object to crown

- src/api/bkuser_core/bkiam/constants.py
- src/api/bkuser_core/categories/management/commands/test_category_sync.py
- src/api/bkuser_core/categories/plugins/base.py
- src/api/bkuser_core/categories/plugins/custom/client.py
- src/api/bkuser_core/categories/plugins/custom/helpers.py
- src/api/bkuser_core/categories/plugins/ldap/adaptor.py
- src/api/bkuser_core/categories/plugins/ldap/client.py
- src/api/bkuser_core/categories/plugins/ldap/helper.py
- src/api/bkuser_core/categories/plugins/ldap/login.py
- src/api/bkuser_core/categories/plugins/ldap/metas.py
- src/api/bkuser_core/categories/plugins/ldap/models.py
- src/api/bkuser_core/categories/plugins/ldap/syncer.py
- src/api/bkuser_core/categories/plugins/utils.py
- src/api/bkuser_core/categories/tasks.py
- src/api/bkuser_core/categories/views.py
- src/api/bkuser_core/tests/categories/plugins/conftest.py
- src/api/bkuser_core/tests/categories/plugins/custom/test_helper.py
- src/api/bkuser_core/tests/categories/plugins/ldap/test_adaptor.py
- src/api/bkuser_core/tests/categories/plugins/ldap/test_client.py
- src/api/bkuser_core/tests/categories/plugins/ldap/test_helper.py
- src/api/bkuser_core/tests/categories/plugins/ldap/test_syncer.py
- src/api/bkuser_core/tests/conftest.py
close https://github.com/TencentBlueKing/bk-user/issues/27
> refactor: 重构 LDAP 协议的用户同步逻辑, 使其统计同步成功或失败的对象

- src/api/bkuser_core/categories/plugins/ldap/handlers.py
- src/api/bkuser_core/common/exception_handler.py
- src/api/bkuser_core/common/serializers.py
- src/api/bkuser_core/common/viewset.py
- src/api/bkuser_core/profiles/views.py
- src/api/bkuser_core/user_settings/signals.py
- src/api/bkuser_core/user_settings/views.py
没有把 sdk 的同步更新放到这个 MR 中，方便 review
closes #26
> fix: adding query_serializer for profiles batch retrieve #26

- src/api/bkuser_core/departments/serializers.py
- src/api/bkuser_core/departments/views.py
$ curl --location --request POST 'http://192.168.0.200:32780/api/v2/departments/' --data-raw ''
```
ERROR [2021-09-11 17:12:30] bkuser_core.common.exception_handler(ln:81): request apiServer failed
Traceback (most recent call last):
File "/tmp/venv/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/tmp/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
return bound_method(*args, **kwargs)
File "/tmp/123321/bk-user/src/api/bkuser_core/common/cache.py", line 38, in wrapper
value = func(*args, **kwargs)
File "/tmp/123321/bk-user/src/api/bkuser_core/departments/views.py", line 184, in create
category = ProfileCategory.objects.get(id=validated_data["category_id"])
KeyError: …
```
> Fix /api/v2/departments/(POST) parameter KeyError

- src/api/bkuser_core/categories/views.py
- src/api/bkuser_core/common/viewset.py
- src/api/bkuser_core/departments/views.py
- src/api/bkuser_core/profiles/views.py
- src/api/bkuser_core/tests/apis/categories/test_categories.py
- src/api/bkuser_core/tests/apis/departments/test_departments.py
- src/api/bkuser_core/tests/apis/profiles/test_profiles_list.py
Signed-off-by: Chenyang Yan <memory.yancy@gmail.com>
> Fix issue1 -- Support retrive soft delete userlists info

- src/pages/src/views/organization/details/DetailsBar.vue
> fix: 上级数据展示问题bug处理

- src/pages/src/views/organization/details/DetailsBar.vue
> fix: 直接上级下拉框bug修复

- src/pages/src/views/organization/details/DetailsBar.vue
> fix: 添加用户侧边栏空白bug处理

- src/pages/src/Header.vue
- src/pages/src/components/authority/NoAuthority.vue
- src/pages/src/components/catalog/home/ExportUser.vue
- src/pages/src/components/catalog/operation/SetPassword.vue
- src/pages/src/components/organization/ExportTree.vue
- src/pages/src/components/organization/SetDepartment.vue
- src/pages/src/scss/bk_icon_font/demo.html
- src/pages/src/views/audit/index.vue
- src/pages/src/views/catalog/PageAdd.vue
- src/pages/src/views/catalog/PageHome.vue
- src/pages/src/views/catalog/dataUpdate.vue
- src/pages/src/views/organization/details/DetailsBar.vue
- src/pages/src/views/organization/details/InputComponents.vue
- src/pages/src/views/organization/details/UserMaterial.vue
- src/pages/src/views/organization/index.vue
- src/pages/src/views/organization/table/UserTable.vue
- src/pages/src/views/organization/tree/DialogContent.vue
- src/pages/src/views/organization/tree/OrganizationTree.vue
- src/pages/src/views/organization/tree/TreeSearch.vue
- src/pages/src/views/password/Modify.vue
- src/pages/src/views/setting/FieldsAdd.vue
- src/pages/src/views/setting/FieldsSetting.vue
format: 表单，表格，列表添加data-test-id
> format: 表单，表格，列表添加data-test-id

- src/api/bkuser_core/departments/urls.py
> fix: 修复当部门名存在 . 时 Api 查找 404 问题 #147

- src/api/Dockerfile
- src/login/Dockerfile
- src/login/poetry.lock
- src/saas/Dockerfile
according to https://github.com/python-poetry/poetry/issues/3591
> fix poetry install packages fail

- src/saas/bkuser_shell/common/exceptions.py
> fix(exception): blueException missing message detail while logging or print

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
nothing changed, except the tag name
> chore(helm/charts): update version to v2.3.4-beta.12

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/templates/deployment.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
- src/saas/bkuser_shell/config/common/system.py
- src/saas/bkuser_shell/monitoring/urls.py
- src/saas/bkuser_shell/monitoring/views.py
> Ft saas ping

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
- src/api/bkuser_core/enhanced_account/authentication.py
- src/login/bklogin/components/usermgr_api.py
- 多重身份验证, 调整顺序
- login 调用bk-user api增加: get_profile_by_code
> feat(api): change multiple auth order, add one more bk-user api in login

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
- src/api/bkuser_core/enhanced_account/authentication.py
- 修复token auth顺序导致saas 无法访问API
> Fix saas call api fail

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
- src/api/bkuser_core/user_settings/migrations/0007_auto_20210703_2020.py
migration: https://github.com/TencentBlueKing/bk-user/blob/development/src/api/bkuser_core/user_settings/migrations/0007_auto_20210703_2020.py#L24
init_settings: https://github.com/TencentBlueKing/bk-user/blame/development/src/api/bkuser_core/categories/plugins/plugin.py#L71
conflict with the same name
-----
solution:
- change migration insert from `create` to `get_or_create`
> fix(user_settings/migration): migration setttings_meta create same key with the init_settings

- src/api/bkuser_core/categories/plugins/custom/client.py
> fix(api/categories): fix custom sync via http will raise IndexError if results is empty

- src/login/bklogin/api/constants.py
- src/login/bklogin/api/utils.py
- src/login/bklogin/backends/bk.py
- src/login/bklogin/bk_i18n/__init__.py
- src/login/bklogin/bk_i18n/apps.py
- src/login/bklogin/bk_i18n/middlewares.py
- src/login/bklogin/bk_i18n/signal_receivers.py
- src/login/bklogin/bkaccount/admin.py
- src/login/bklogin/bkaccount/manager.py
- src/login/bklogin/bkauth/forms.py
- src/login/bklogin/bkauth/middlewares.py
- src/login/bklogin/bkauth/models.py
- src/login/bklogin/bkauth/utils.py
- src/login/bklogin/common/usermgr.py
- src/login/bklogin/components/esb.py
- src/login/bklogin/components/http.py
- src/login/bklogin/components/license.py
- src/login/bklogin/components/usermgr_api.py
- src/login/bklogin/components/util.py
- src/saas/bkuser_shell/common/exceptions.py
- 移除日志中的敏感信息
- 清理login遗留的 `from __future__ import unicode_literals`
> fix(login): logger remove sensitive info from data

- src/api/bkuser_core/categories/models.py
- src/api/bkuser_core/categories/tasks.py
> fix(api/sync_data): custom sync from crontab use the same task_id

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
- 国际化 (#417)
- Custom profile sync add original `code` into `extras` (#420)
- Change CELERY_RESULT_BACKEND to django-db, instead of MQ or Redis (#419)
- Plugin init_settings add more detail in log info (#422)
- Add unique_together for user_settings_setting(category_id+meta_id) (#425)
> chore(helm): 1.2.13

- src/api/bkuser_core/common/error_codes.py
- src/api/bkuser_core/profiles/v2/views.py
- src/login/bklogin/backends/bk.py
> feat(login/log): add more log detail in login process

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
- src/api/poetry.lock
- src/api/pyproject.toml
- src/saas/poetry.lock
- src/saas/pyproject.toml
- 更新poetry中 importlib-metadata 版本(二进制部署报错)
> Ft poetry lib

- src/api/bkuser_core/profiles/migrations/0025_dynamic_field_add_account_expiration_date.py
变更点：
修改： 修改用户创建时间、最近登录时间为管理员不可编辑
> 增设账号过期内置字段#398

- src/saas/bkuser_shell/common/constants.py
- src/saas/bkuser_shell/common/export.py
> bug_fix: DDE注入漏洞解决，设置导入导出模板单元格为文本模式

- src/api/bkuser_core/bkiam/constants.py
> fix(iam/sync_task): key error while running

- src/login/bklogin/backends/bk.py
- src/login/bklogin/bkauth/views.py
- src/login/bklogin/common/exceptions.py
- src/login/bklogin/templates/account/login_ce.html
> bugfix: 前端账户有效期展示异常

- src/saas/bkuser_shell/common/export.py
- src/sdk/bkuser_sdk/models/profile.py
> bugfix: 修复导出用户数据乱位问题

- src/api/bkuser_core/profiles/tasks.py
- src/api/bkuser_core/user_settings/migrations/0002_auto_20191104_1600.py
feature: 新增账户冻结周期任务 #issue 538
> feature: 新增账户冻结周期任务 issue 538

- src/saas/bkuser_shell/common/export.py
> refactor: 代码结构优化

- src/api/bkuser_core/profiles/password_expiration_notifier.py
- src/api/bkuser_core/profiles/tasks.py
- src/api/bkuser_core/user_settings/constants.py
- src/api/bkuser_core/user_settings/migrations/0017_add_default_fields_password_settings.py
##变更点：
新增：密码过期提醒
##相关issue
https://github.com/TencentBlueKing/bk-user/issues/117
> feat:密码过期提醒issue#117

- src/api/bkuser_core/profiles/account_expiration_notifier.py
- src/api/bkuser_core/profiles/migrations/0025_dynamic_field_add_account_expiration_date.py
- src/api/bkuser_core/profiles/notifier.py
- src/api/bkuser_core/profiles/password_expiration_notifier.py
- src/api/bkuser_core/profiles/tasks.py
- src/api/bkuser_core/user_settings/migrations/0017_add_default_fields_password_settings.py
> fix:过期通知部分整合优化

- src/pages/src/Header.vue
- src/pages/src/views/organization/details/InputString.vue
- src/pages/src/views/organization/tree/TreeSearch.vue
> fix: 邮箱正则校验 #549

- src/api/bkuser_core/profiles/tasks.py
refactor: 定时冻结扫描任务，新增场景考虑:该用户被管理员关注
> refactor: 定时冻结扫描任务，新增场景考虑:该用户被管理员关注

- src/api/bkuser_core/categories/plugins/local/syncer.py
feature: 本地目录导入用户，新增根据密码初始化设置，是否发送密码邮件
> feature: 本地目录导入用户，新增根据密码初始化设置，是否发送密码邮件

- src/api/bkuser_core/profiles/utils.py
> fix(api/profile): change random passowrd rule

- deploy/helm/bk-user/Chart.yaml
- deploy/helm/bk-user/charts/api/Chart.yaml
- deploy/helm/bk-user/charts/api/values.yaml
- deploy/helm/bk-user/charts/login/Chart.yaml
- deploy/helm/bk-user/charts/login/values.yaml
- deploy/helm/bk-user/charts/saas/Chart.yaml
- deploy/helm/bk-user/charts/saas/values.yaml
- src/api/bkuser_core/categories/plugins/local/syncer.py
- src/api/bkuser_core/categories/views.py
- src/api/bkuser_core/departments/v2/views.py
- src/api/bkuser_core/departments/v3/views.py
- src/api/bkuser_core/profiles/utils.py
- src/api/bkuser_core/profiles/v2/views.py
- src/api/bkuser_core/profiles/v3/views.py
- src/api/bkuser_core/user_settings/views.py
- src/saas/bkuser_shell/config_center/views.py
- src/saas/bkuser_shell/organization/views/departments.py
- src/saas/bkuser_shell/organization/views/profiles.py
* fix(iam): api viewset iam settings
> fix(iam): api viewset iam settings (#614)

- src/api/bkuser_core/profiles/v2/views.py
> fix(api/profiles): /api/v2/profiles fetch last_login_time cause huge query

- src/api/bkuser_core/profiles/v2/serializers.py
- src/api/bkuser_core/profiles/v2/views.py
- src/saas/RELEASE.yaml
> fix(export): audit login log export and version log

- src/api/bkuser_core/api/web/home/serializers.py
- src/api/bkuser_core/api/web/home/views.py
- src/api/bkuser_core/categories/cache.py
- src/api/bkuser_core/config/common/storage.py
- src/api/bkuser_core/departments/cache.py
- src/api/bkuser_core/departments/models.py
- src/api/bkuser_core/profiles/cache.py
fix #722 
1. department的`full_name`/`has_children`增加短时内存cache
> performance 

- src/api/bkuser_core/bkiam/permissions.py
- src/pages/src/views/organization/table/PullUser.vue
bugfix:
1. 用户不属于任何部门, 操作鉴权报错
2. 从别的部门拉取用户, 搜索无结果
> Bugfix permission raise

- src/api/bkuser_core/common/exception_handler.py
> feat(api return): full error detail when auth failed

- src/api/wsgi.py
- src/config.json
- src/login/wsgi.py
- src/saas/wsgi.py
> feat(wsgi/faulthandler): enable faulthandler in wsgi.py

- src/api/bkuser_core/api/web/profile/views.py
> fix(profile/create): fail when got no settings of expired_after_days

- src/api/bkuser_core/api/web/audit/serializers.py
> fix(audit/export): export fail when got ugettext_lazy

- src/api/bkuser_core/categories/plugins/local/syncer.py
issue：https://github.com/TencentBlueKing/bk-user/issues/728
> fix:lint check #issue728

- src/api/bkuser_core/api/login/views.py
- src/api/bkuser_core/tests/apis/v2/profiles/test_login.py
issue：https://github.com/TencentBlueKing/bk-user/issues/810
> feat: 登录密码试错锁定机制取消对admin用户豁免 #810

- src/api/bkuser_core/api/web/audit/serializers.py
相关issue：https://github.com/TencentBlueKing/bk-user/issues/618
> feat: 导出增加<全名> #618

- src/pages/src/components/catalog/home/ImportUser.vue
- src/pages/src/store/modules/catalog.js
- src/pages/src/views/audit/index.vue
- src/pages/src/views/catalog/PageHome.vue
1、审计日志中新增人员全名列&导出列表优化 #618 
2、通过excel导入用户组织支持全量更新 #728
> feature: 1、审计日志中新增人员全名列&导出列表优化 #618 2、通过excel导入用户组织支持全量更新 #728

- src/pages/src/views/organization/details/UserMaterial.vue
feature: admin账户重置密码需要先输入原密码进行校验 #811
> feature: admin账户重置密码需要先输入原密码进行校验 #811

- src/api/bkuser_core/api/web/category/serializers.py
- src/api/bkuser_core/api/web/department/serializers.py
- src/api/bkuser_core/api/web/home/serializers.py
- src/api/bkuser_core/api/web/home/views.py
- src/api/bkuser_core/departments/models.py
fix #904 
- 合并 原目录列表接口到 组织架构home/tree接口 (相当于平迁了slz)
- 部门加入 profile_count 支持页面点击展示
> feat(home/tree): add more category attributes; add department detail with profile_count

- src/api/bkuser_core/categories/plugins/plugin.py
- src/api/bkuser_core/tests/categories/plugins/test_plugin.py
> fix(category/plugin): fix category been configured after reload

- src/api/bkuser_core/api/web/category/serializers.py
- src/api/bkuser_core/api/web/category/views.py
- src/api/bkuser_core/api/web/department/serializers.py
- src/api/bkuser_core/api/web/department/views.py
- src/api/bkuser_core/api/web/serializers.py
- src/api/bkuser_core/api/web/utils.py
> refactor(profiles/api): change departments and categories profiles api

- src/api/bkuser_core/api/login/serializers.py
- src/api/bkuser_core/api/login/views.py
> feat(login/api): support iso_code for query and upsert

- src/api/bkuser_core/apis/urls.py
通过DEBUG参数区分环境，从而是否放开swagger路由
fix #934
> fix(bkuser_core/apis/urls.py): 生产环境下屏蔽swagger路由

- src/api/bkuser_core/api/login/views.py
- src/api/bkuser_core/audit/constants.py
- src/api/bkuser_core/common/error_codes.py
离职状态下的用户禁止登录
相关issue：https://github.com/TencentBlueKing/bk-user/issues/929
> feat:check staff status before login #929

- src/login/bklogin/bkauth/utils.py
修复登出失败，登录token未做unquote
re: https://github.com/TencentBlueKing/bk-user/issues/950
> fix: 修复登出失败，登录token未做unquote

- src/api/bkuser_core/categories/plugins/ldap/login.py
拉取全部用户，变更为针对username进行拉取
re #927 #783
> refactor(categories/plugins/ldap/login.py): 优化用户量大的mad/ldap下用户登录，耗时长

- src/saas/bkuser_shell/config/overlays/prod.py
- src/saas/bkuser_shell/config/overlays/stag.py
> feat(saas): static file url support read from env for bk cdn

- src/api/bkuser_core/api/web/category/views.py
> fix(web/category): ldap/mad目录配置拉取周期不生效

- src/api/bkuser_core/api/web/audit/views.py
相关issue：https://github.com/TencentBlueKing/bk-user/issues/964
> feat: 登录审计支持模糊搜索用户名 #964

- src/pages/src/common/util.js
- src/pages/src/views/organization/details/UserMaterial.vue
1、添加多选的枚举字段后，用户详情和编辑用户展示状态不一致
2、账号过期时间逻辑调整
> fix: bug修复

- src/pages/src/views/setting/FieldsAdd.vue
> fix: 修复枚举字段多选值展示问题

- src/api/bkuser_core/api/web/department/views.py
> refactor(web/department/view.py): 补充组织架构删除操作的审计日志

- src/api/bkuser_core/profiles/v2/serializers.py
- src/api/bkuser_core/profiles/v2/urls.py
- src/api/bkuser_core/profiles/v2/views.py
re: https://github.com/TencentBlueKing/bk-user/issues/1005
> feat(api): support update user's language

- src/api/bkuser_core/api/web/profile/serializers.py
相关issue：https://github.com/TencentBlueKing/bk-user/issues/1008
修复：清空用户的职务字段后保存会发生异常
> fix：position职务允许非必填 #1008

- src/api/bkuser_core/api/web/field/serializers.py
> fix(web/field): 修复字段名称更新和可编辑性不生效

- src/pages/src/Header.vue
- src/pages/src/views/organization/details/DetailsBar.vue
- src/pages/src/views/organization/details/UserMaterial.vue
- src/pages/src/views/organization/index.vue
> fix: bugfix

- src/api/bkuser_core/api/web/profile/views.py
- src/api/bkuser_core/common/error_codes.py
- src/api/bkuser_core/profiles/v2/views.py
- src/api/bkuser_core/profiles/validators.py
> refactor(profile): 保存用户提示优化

- src/api/bkuser_core/api/web/password/views.py
- src/api/bkuser_core/common/error_codes.py
忘记密码功能，异常用户提示优化，不返回空相应，默认成功
refactor #1099
> refactor(password): 忘记密码功能，异常用户提示优化

- src/api/bkuser_core/api/web/audit/constants.py
- src/api/bkuser_core/api/web/field/views.py
- src/api/bkuser_core/audit/constants.py
- src/api/bkuser_core/common/error_codes.py
> fix(field): 变更展示字段，增加审计

- src/api/bkuser_core/api/login/views.py
- src/api/bkuser_core/api/web/audit/constants.py
- src/api/bkuser_core/audit/constants.py
修复禁用/被删除用户登录，登记审计日志显示异常
fix #1107
> fix(profile.login_check): 修复禁用/被删除用户登录，登记审计日志显示异常

- src/bk-user/bkuser/apis/web/tenant/views.py
> refactor(swagger): swagger配置

- src/bk-user/bkuser/apps/data_source/models.py
- src/bk-user/bkuser/apps/tenant/models.py
- src/bk-user/bkuser/biz/tenant_admin.py
> fix(tenant): 展示接口修复

- src/api/bkuser_core/api/web/audit/constants.py
- src/api/bkuser_core/api/web/field/views.py
- src/api/bkuser_core/api/web/password/views.py
- src/api/bkuser_core/audit/constants.py
- src/api/bkuser_core/common/error_codes.py
1. 忘记密码功能，异常用户提示优化
2. 变更展示字段，增加审计
fix #1099 
fix #1102
> fix(web): 问题修复

- src/pages/src/common/regex.ts
- src/pages/src/http/fetch/index.ts
- src/pages/src/views/setting/FieldSetting.vue
- src/pages/src/views/setting/FieldsAdd.vue
- src/pages/src/views/tenant/group-details/MemberSelector.vue
- src/pages/src/views/tenant/group-details/OperationDetails.vue
> feat: 添加字段、编辑字段静态页面

- src/bk-user/bkuser/apis/web/organization/views.py
- src/bk-user/bkuser/apis/web/tenant/serializers.py
> fix: 联调测试修复

- src/bk-user/bkuser/apis/web/mixins.py
- src/bk-user/bkuser/apis/web/organization/serializers.py
- src/bk-user/bkuser/apis/web/organization/urls.py
- src/bk-user/bkuser/apis/web/organization/views.py
- src/bk-user/bkuser/apis/web/tenant/serializers.py
- src/bk-user/bkuser/biz/data_source.py
- src/bk-user/bkuser/biz/tenant.py
- src/bk-user/bkuser/common/error_codes.py
> feat(organization): 新增租户下用户列表接口

- src/bk-user/bkuser/apis/web/organization/views.py
> fix(organization): 联调修复

- src/bk-user/bkuser/apis/web/tenant/serializers.py
- src/bk-user/bkuser/biz/tenant.py
fix update tenant without updated_at
> fix(organization): fix update tenant without updated_at

- src/bk-user/bkuser/apis/web/mixins.py
- src/bk-user/bkuser/apis/web/organization/views.py
> fix(organization): 修复展示没有协同关系的租户

- src/api/bkuser_core/api/login/views.py
- src/api/bkuser_core/api/web/audit/constants.py
- src/api/bkuser_core/audit/constants.py
修复禁用/被删除用户登录，登记审计日志显示异常
fix #1107
> refactor(profile.login_check): 修复禁用/被删除用户登录，登记审计日志显示异常

- src/api/bkuser_core/api/web/password/serializers.py
- src/api/bkuser_core/api/web/password/views.py
- src/pages/src/views/password/Modify.vue
> fix: 修复个人中心，修改密码token丢失

- src/bk-user/bkuser/apis/web/tenant_setting/serializers.py
> fix: validate tenant_user_fields

- src/bk-user/bkuser/apis/web/data_source_organization/serializers.py
- src/bk-user/bkuser/apis/web/data_source_organization/views.py
> fix: 上级不能是自己

- src/pages/src/http/settingFiles.ts
- src/pages/src/utils/index.ts
- src/pages/src/views/data-source/new-data/Local.vue
- src/pages/src/views/setting/AccountSetting.vue
- src/pages/src/views/tenant/group-details/OperationDetails.vue
> feat: 账号有效期接口联调

- src/bk-user/bkuser/apis/login/serializers.py
> fix(bklogin): local user auth wrong

- src/pages/src/app.vue
- src/pages/src/views/Header.vue
> feat: 角色导航权限

- src/bk-user/bkuser/apis/web/data_source/serializers.py
- src/bk-user/bkuser/apis/web/data_source/views.py
- src/bk-user/bkuser/apis/web/idp/schema.py
- src/bk-user/bkuser/apis/web/idp/serializers.py
- src/bk-user/bkuser/apis/web/idp/urls.py
- src/bk-user/bkuser/apis/web/idp/views.py
- src/bk-user/bkuser/apps/permission/permissions.py
- src/bk-user/bkuser/common/error_codes.py
- src/bk-user/tests/apis/web/data_source/test_data_source.py
- src/bk-user/tests/apis/web/idp/test_idp.py
- 获取插件配置json_schema API，前端根据json_schema渲染表单
> feat(idp): plugin config meta retrieve api

- src/bk-login/bklogin/settings.py
- src/bk-login/poetry.lock
- src/bk-login/pyproject.toml
> feat(bklogin): support cors settings

- src/bk-login/pages/bk.config.js
- src/bk-login/pages/package.json
- src/bk-login/pages/src/views/home.vue
> feat: 非定制登录跳转

- src/pages/src/views/auth-source/ViewDetails.vue
- src/pages/src/views/auth-source/edit-data/Local.vue
- src/pages/src/views/auth-source/edit-data/WeCom.vue
- src/pages/src/views/auth-source/new-data/WeCom.vue
- src/pages/src/views/auth-source/new-data/index.vue
- src/pages/src/views/data-source/new-data/Http.vue
- src/pages/src/views/organization/index.vue
> fix: 体验问题修复

- src/bk-login/bklogin/authentication/urls.py
- src/bk-login/bklogin/authentication/views.py
- src/bk-login/bklogin/component/bk_user/api.py
- src/bk-login/bklogin/component/bk_user/models.py
- src/bk-user/bkuser/apis/login/serializers.py
- src/bk-user/bkuser/apis/login/urls.py
- src/bk-user/bkuser/apis/login/views.py
- src/bk-user/tests/apis/login/__init__.py
- src/bk-user/tests/apis/login/test_auth.py
> feat(login): opt when only enable auth tenant

- src/pages/src/http/tenantsFiles.ts
- src/pages/src/http/types/tenantsFiles.ts
- src/pages/src/views/setting/FieldsAdd.vue
- src/pages/src/views/tenant/group-details/index.vue
> feat: 租户可见性接口联调

- src/bk-user/bkuser/apis/web/personal_center/serializers.py
- src/bk-user/bkuser/apis/web/personal_center/urls.py
- src/bk-user/bkuser/apis/web/personal_center/views.py
- src/bk-user/tests/apis/web/natural_user/test_natural_user.py
> feat: 个人中心支持头像变更

- src/bk-user/bkuser/apis/web/personal_center/serializers.py
- src/bk-user/bkuser/apis/web/personal_center/views.py
> fix: 个人中心关联用户列表支持logo查看

- src/pages/src/hooks/use-validate.ts
- src/pages/src/views/data-source/local-details/EditUser.vue
- src/pages/src/views/data-source/new-data/Http.vue
- src/pages/src/views/data-source/new-data/Local.vue
- src/pages/src/views/organization/details/EditDetailsInfo.vue
- src/pages/src/views/setting/FieldSetting.vue
- src/pages/src/views/setting/FieldsAdd.vue
- src/pages/src/views/tenant/group-details/MemberSelector.vue
- src/pages/src/views/tenant/group-details/OperationDetails.vue
> fix: 自定义枚举字段交互变更

- src/bk-user/bkuser/apis/login/serializers.py
> fix(bklogin): should not tip of username rule when auth certs

- build.yml
- src/pages/src/components/custom-fields/index.vue
- src/pages/src/components/custom-fields/view.vue
- src/pages/src/hooks/useCustomFields.ts
- src/pages/src/views/data-source/local-details/EditUser.vue
- src/pages/src/views/data-source/local-details/UserInfo.vue
- src/pages/src/views/data-source/local-details/ViewUser.vue
- src/pages/src/views/data-source/new-data/Http.vue
- src/pages/src/views/data-source/new-data/Local.vue
- src/pages/src/views/data-source/new-data/index.less
- src/pages/src/views/organization/details/UserInfo.vue
- src/pages/src/views/organization/details/ViewUser.vue
- src/pages/src/views/personal-center/index.vue
- src/pages/src/views/setting/FieldsAdd.vue
> feat: 自定义字段使用

- src/pages/.gitignore
- src/pages/package.json
- src/pages/src/components/schema-form/SchemaForm.vue
- src/pages/src/hooks/useCustomPlugin.ts
- src/pages/src/http/authSourceFiles.ts
- src/pages/src/views/auth-source/ViewDetails.vue
- src/pages/src/views/auth-source/edit-data/CustomPlugin.vue
- src/pages/src/views/auth-source/edit-data/WeCom.vue
- src/pages/src/views/auth-source/edit-data/index.vue
- src/pages/src/views/auth-source/new-data/CustomPlugin.vue
- src/pages/src/views/auth-source/new-data/WeCom.less
- src/pages/src/views/auth-source/new-data/index.vue
- src/pages/yarn.lock
> feat: 通用认证源配置

- src/pages/src/components/schema-form/SchemaForm.vue
- src/pages/src/views/auth-source/new-data/CustomPlugin.vue
> feat: 通用认证源配置优化

- src/pages/package.json
- src/pages/src/css/tenantEditStyle.less
- src/pages/src/css/tenantViewStyle.less
- src/pages/src/hooks/use-validate.ts
- src/pages/src/http/dataSourceFiles.ts
- src/pages/src/views/data-source/local-details/UserInfo.vue
- src/pages/src/views/organization/details/DetailsInfo.vue
- src/pages/src/views/organization/details/EditDetailsInfo.vue
- src/pages/src/views/organization/index.vue
- src/pages/src/views/tenant/group-details/OperationDetails.vue
- src/pages/src/views/tenant/group-details/index.vue
- src/pages/yarn.lock
> feat: 展示数据源用户所属部门组织路径

- src/pages/src/hooks/useButtonFixed.ts
- src/pages/src/hooks/useCustomPlugin.ts
- src/pages/src/views/auth-source/edit-data/CustomPlugin.vue
- src/pages/src/views/auth-source/edit-data/Local.vue
- src/pages/src/views/auth-source/edit-data/WeCom.vue
- src/pages/src/views/auth-source/edit-data/index.vue
- src/pages/src/views/auth-source/new-data/CustomPlugin.vue
- src/pages/src/views/auth-source/new-data/WeCom.less
- src/pages/src/views/auth-source/new-data/WeCom.vue
- src/pages/src/views/auth-source/new-data/index.vue
- src/pages/src/views/organization/details/EditDetailsInfo.vue
- src/pages/src/views/tenant/group-details/OperationDetails.vue
> refactor: 吸底按钮代码优化

- .github/workflows/eslint.yml
> feat: 因网络问题，暂时注释ESLint扫描

- src/pages/src/views/organization/details/DetailsBar.vue
- src/pages/src/views/organization/details/InputPhone.vue
> fix: 手机号校验修复

- src/bk-login/pages/src/app.vue
- src/bk-login/pages/src/views/home.vue
> fix: 优化清除租户ID

- .gitignore
- src/pages/src/components/ResetPassword.vue
- src/pages/src/css/tenantViewStyle.less
- src/pages/src/http/dataSourceFiles.ts
- src/pages/src/http/types/dataSourceFiles.ts
- src/pages/src/views/data-source/LocalDataSource.vue
- src/pages/src/views/data-source/local-details/PswInfo.vue
- src/pages/src/views/data-source/local-details/UserInfo.vue
- src/pages/src/views/data-source/local-details/index.vue
- src/pages/src/views/data-source/new-data/Local.vue
- src/pages/src/views/organization/details/DetailsInfo.vue
- src/pages/src/views/tenant/group-details/OperationDetails.vue
> feat: 数据源用户重置密码

- src/api/bkpkg-usermgr.yaml
- src/saas/bkpkg-bk_user_manage.yaml
- 添加 saas 和 api 的 bkpkg.yaml 版本依赖声明文件
> build: add bkpkg yaml of api and saas

- src/bk-login/pages/package.json
- src/bk-login/pages/src/views/home.vue
> feat: 文案修改

- src/bk-user/bkuser/apis/web/data_source_organization/serializers.py
- src/bk-user/bkuser/apis/web/data_source_organization/views.py
- src/bk-user/bkuser/apis/web/personal_center/serializers.py
- src/bk-user/bkuser/apis/web/personal_center/urls.py
- src/bk-user/bkuser/apis/web/personal_center/views.py
- src/bk-user/bkuser/biz/data_source_organization.py
- src/bk-user/bkuser/biz/validators.py
> feat: support user change pwd in personal center

- src/pages/package.json
- src/pages/src/components/custom-fields/index.vue
- src/pages/src/components/custom-fields/view.vue
- src/pages/src/hooks/useCustomFields.ts
- src/pages/src/http/personalCenterFiles.ts
- src/pages/src/http/types/settingFiles.ts
- src/pages/src/router/index.ts
- src/pages/src/utils/index.ts
- src/pages/src/views/NotFound.vue
- src/pages/src/views/personal-center/index.vue
- src/pages/src/views/setting/FieldSetting.vue
- src/pages/src/views/setting/FieldsAdd.vue
- src/pages/yarn.lock
> fix: 自定义字段修改 & 枚举值删除

- src/pages/src/components/ResetPassword.vue
- src/pages/src/hooks/useTableFields.ts
- src/pages/src/utils/index.ts
- src/pages/src/views/data-source/local-details/UserInfo.vue
- src/pages/src/views/organization/details/UserInfo.vue
- src/pages/src/views/organization/index.vue
- src/pages/src/views/personal-center/index.vue
> fix: 表格设置自定义字段交互

- src/pages/src/components/ChangePassword.vue
- src/pages/src/http/personalCenterFiles.ts
- src/pages/src/http/types/personalCenterFiles.ts
- src/pages/src/views/personal-center/index.vue
> feat: 个人中心修改密码

- .gitignore
- src/pages/package-lock.json
- src/pages/package.json
- src/pages/src/views/organization/index.vue
> fix: 组件升级，搜索交互优化

- src/pages/src/views/setting/FieldSetting.vue
- src/pages/src/views/setting/FieldsAdd.vue
> fix: 自定义字段删除枚举值交互优化

- src/pages/src/views/password/Modify.vue
> fix: 修改密码前获取用户信息

- src/bk-user/bkuser/apps/idp/management/__init__.py
- src/bk-user/bkuser/apps/idp/management/commands/__init__.py
- src/bk-user/bkuser/apps/idp/management/commands/register_idp_plugin.py
- src/idp-plugins/idp_plugins/constants.py
> feat(cmd): add register idp plugin

- src/idp-plugins/idp_plugins/base.py
> fix(idp_plugin): id error when register custom plugin

- src/api/bkuser_core/api/web/profile/serializers.py
- src/api/bkuser_core/common/db_sync.py
- src/login/bklogin/templates/login.html
- src/saas/bkuser_shell/proxy/proxy.py
Fixes：
1.  #1136 
2.  #1268 
3. pick #1008
4. login username输入不保留历史输入
> fix：2.5.3 bug遗留

- src/bk-login/bklogin/authentication/urls.py
- src/bk-user/bkuser/common/renderers.py
> fix: response not data when 204

- src/pages/package.json
- src/pages/yarn.lock
> fix: bkui-vue

- src/pages/src/views/organization/details/DetailsBar.vue
> fix: 2.x直接上级搜索优化

- src/pages/src/views/organization/details/DetailsBar.vue
> fix: 2.5直接上级搜索优化

- src/pages/src/plugins/methods.js
- src/pages/src/views/organization/details/DetailsBar.vue
> fix: 2.5.3直接上级搜索优化

- src/pages/src/views/data-source/new-data/Local.vue
> fix: 初始密码通知模板问题修复

- .pre-commit-config.yaml
- src/bk-login/bklogin/authentication/utils.py
- src/bk-login/bklogin/authentication/views.py
- src/bk-login/bklogin/settings.py
- src/bk-login/tests/authentication/__init__.py
- src/bk-login/tests/authentication/test_utils.py
- src/bk-user/bkuser/settings.py
> feat(login): check if the callback address is safe

- src/pages/src/app.vue
> fix: 代码优化 #1570

- src/bk-user/bkuser/component/login.py
> fix(bkuser): rasie exception when bk_token is invalid

- src/login/poetry.lock
- src/login/pyproject.toml
- add pycryptodomex for login plugin
> feat(bklogin): add pycryptodomex for login plugin

- src/login/poetry.lock
- src/login/pyproject.toml
- use pycryptodomex pkg replace pyCrypto
> feat(bklogin): use pycryptodomex pkg replace pyCrypto

- src/login/poetry.lock
- src/login/pyproject.toml
> feat(bklogin): add pycryptodome pkg

- src/bk-user/bkuser/apis/web/platform_management/serializers.py
- src/bk-user/bkuser/apps/tenant/models.py
- src/bk-user/bkuser/common/constants.py
> fix: phone allow blank when create tenant

- src/bk-login/pages/src/views/home.vue
> feat: 添加忘记密码入口 #1570

- src/bk-user/bkuser/apis/web/tenant_info/mixins.py
- src/bk-user/bkuser/apis/web/tenant_info/serializers.py
- src/bk-user/bkuser/apis/web/tenant_info/views.py
> feat: update builtin manager api modify from put to patch

- src/bk-user/bkuser/apis/web/tenant_info/serializers.py
- src/bk-user/bkuser/apis/web/tenant_info/urls.py
- src/bk-user/bkuser/apis/web/tenant_info/views.py
> feat(bkuser): add web api - add tenant manager / remove tenant manager

- src/pages/src/components/MemberSelector.vue
- src/pages/src/http/settingFiles.ts
- src/pages/src/http/types/settingFiles.ts
- src/pages/src/views/setting/AdminSetting.vue
> fix: 管理员配置交互优化 #1589

- src/login/bklogin/templates/login.html
> feat(login): remove copyright in footer

- src/bk-user/bkuser/apis/web/urls.py
- src/bk-user/bkuser/apis/web/virtual_user/__init__.py
- src/bk-user/bkuser/apis/web/virtual_user/mixins.py
- src/bk-user/bkuser/apis/web/virtual_user/serializers.py
- src/bk-user/bkuser/apis/web/virtual_user/urls.py
- src/bk-user/bkuser/apis/web/virtual_user/views.py
- src/bk-user/bkuser/apps/data_source/models.py
- src/bk-user/bkuser/apps/idp/models.py
- src/bk-user/tests/apis/web/data_source/conftest.py
- src/bk-user/tests/test_utils/tenant.py
> feat(bkuser): virtual user web api

- src/pages/src/views/organization/details/DetailsBar.vue
- src/pages/src/views/organization/details/InputComponents.vue
- src/pages/src/views/organization/details/InputPhone.vue
- src/pages/src/views/organization/index.vue
- src/pages/src/views/organization/tree/OrganizationTree.vue
> fix：2.5.3修复

- src/pages/src/components/layouts/DataSourceCard.vue
- src/pages/src/hooks/index.ts
- src/pages/src/hooks/useDataSource.ts
- src/pages/src/hooks/useInfoBoxContent.ts
- src/pages/src/http/tenantsFiles.ts
- src/pages/src/views/Header.vue
- src/pages/src/views/setting/AdminSetting.vue
- src/pages/src/views/setting/data-source/ConfigList.vue
- src/pages/src/views/setting/data-source/Success.vue
- src/pages/src/views/tenant/index.vue
> fix: 体验问题修复 #1629

- src/pages/src/components/phoneInput.vue
- src/pages/src/hooks/useValidate.ts
- src/pages/src/http/index.ts
- src/pages/src/http/types/virtualAccount.ts
- src/pages/src/http/virtualAccount.ts
- src/pages/src/router/index.ts
- src/pages/src/views/Header.vue
- src/pages/src/views/audit/index.vue
- src/pages/src/views/virtual-account/EditDetails.vue
- src/pages/src/views/virtual-account/index.vue
> feat: 虚拟账号联调 #1637

- src/pages/package.json
- src/pages/src/common/auth.ts
- src/pages/src/http/fetch/error-interceptor.ts
- src/pages/src/http/fetch/index.ts
- src/pages/src/main.ts
- src/pages/src/views/Header.vue
- src/pages/static/login_success.html
- src/pages/yarn.lock
> fix: window.open #1626

- src/pages/src/common/auth.ts
> feat: 登录跳转修复

- src/pages/src/common/auth.ts
- src/pages/static/login_success.html
> feat: 登录跳转联调

- bkcodeai.json
- src/pages/src/common/auth.ts
- src/pages/src/http/fetch/index.ts
- src/pages/static/login_success.html
> feat: 登录跳转

- src/pages/src/views/organization/details/DetailsBar.vue
> fix: 修复编辑用户时，直接上级未回显问题

- src/pages/src/api/index.js
> fix: 2.x 登录弹窗 #1626

- src/pages/src/api/index.js
- src/pages/static/login_success.html
> fix: 2.x 登录弹框体验问题修复 #1626

- src/pages/src/api/index.js
- src/saas/bkuser_shell/proxy/views.py
- src/saas/bkuser_shell/urls.py
> fix: not url match when login sucess

- src/saas/bkuser_shell/urls.py
> fix: minor

- src/pages/src/http/fetch/index.ts
- src/pages/src/views/setting/LoginSetting.vue
- src/pages/src/views/setting/auth-config/Local.vue
- src/pages/src/views/setting/auth-config/WeCom.vue
- src/pages/yarn.lock
> fix: 登录配置交互优化 #1643

- src/pages/src/components/layouts/MainBreadcrumbs.vue
- src/pages/src/components/layouts/MainView.vue
- src/pages/src/router/index.ts
- src/pages/src/router/router.d.ts
- src/pages/src/store/user.ts
- src/pages/src/views/Header.vue
- src/pages/src/views/setting/FieldSetting.vue
- src/pages/src/views/setting/LoginSetting.vue
- src/pages/src/views/setting/auth-config/Local.vue
- src/pages/src/views/setting/cross-tenant-collaboration/index.vue
- src/pages/src/views/setting/cross-tenant-collaboration/my-share/OperationDetails.vue
- src/pages/src/views/setting/cross-tenant-collaboration/my-share/ViewDetails.vue
- src/pages/src/views/setting/cross-tenant-collaboration/my-share/index.vue
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/OperationDetails.vue
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/index.vue
- src/pages/src/views/setting/data-source/ConfigList.vue
- src/pages/src/views/setting/data-source/NewDataSource.vue
- src/pages/src/views/setting/index.vue
- src/pages/src/views/tenant/OperationDetails.vue
- src/pages/src/views/tenant/index.vue
- src/pages/src/views/virtual-account/EditDetails.vue
- src/pages/src/views/virtual-account/index.vue
> feat: 跨租户协同静态页面 #1684

- src/pages/bk.config.js
- src/pages/package.json
- src/pages/src/views/organization/components/search.vue
- src/pages/yarn.lock
> feat: 更新ESLint

- src/login/Dockerfile
> fix: lock python3-saml dependency package - xmlsec version on 1.3.13

- src/login/Dockerfile
> feat: lock python3-saml dependency package - xmlsec version on 1.3.13

- src/pages/src/views/setting/cross-tenant-collaboration/index.vue
- src/pages/src/views/setting/cross-tenant-collaboration/my-share/index.vue
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/OperationDetails.vue
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/index.vue
- src/pages/src/views/tenant/index.vue
> fix: 跨租户协同交互优化 #1684

- src/pages/src/views/organization/components/aside-tenant.vue
- src/pages/src/views/organization/components/collaboration-item.vue
> fix: 组织树多次请求问题

- src/pages/src/components/field-mapping/FieldMapping.vue
- src/pages/src/hooks/useAdminPassword.ts
- src/pages/src/views/Header.vue
- src/pages/src/views/setting/cross-tenant-collaboration/my-share/OperationDetails.vue
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/OperationDetails.vue
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/index.vue
- src/pages/src/views/tenant/OperationDetails.vue
> fix: 体验问题修复 #1684

- src/pages/src/language/en.json
- src/pages/src/views/Header.vue
- src/pages/src/views/organization/components/blank-page.vue
- src/pages/src/views/tenant/index.vue
> fix: logo无法展示 && 启用提示语

- src/pages/package.json
> feat: 组件库升级

- readme.md
- readme_en.md
- src/bk-user/bkuser/apis/web/collaboration/serializers.py
- src/bk-user/bkuser/apis/web/collaboration/urls.py
- src/bk-user/bkuser/apis/web/collaboration/views.py
- src/bk-user/tests/apis/web/collaboration/test_to_strategy.py
> feat(web api): list collaboration target tenant

- src/pages/src/views/organization/details/UserMaterial.vue
- src/pages/src/views/password/Modify.vue
- src/pages/src/views/password/Set.vue
> feat: 【canway】产品支持iframe加载模式方案（参考标准运维）

- src/pages/src/views/tenant/OperationDetails.vue
- src/pages/src/views/tenant/index.vue
> fix: 创建租户通知方式可以非必填

- src/pages/src/Header.vue
> feat: 注销登录后，bk_ticket 的状态需要设置为已注销

- src/saas/bkuser_shell/config/common/django_basic.py
> feat: remove XFrameOptionsMiddleware to support iframe load

- src/pages/src/views/organization/details/UserMaterial.vue
- src/pages/src/views/password/Modify.vue
- src/pages/src/views/password/Set.vue
> Fix import/release/2.5.3

- src/pages/src/hooks/useOrganizationAside.ts
- src/pages/src/store/app.ts
- src/pages/src/views/organization/components/aside-tenant.vue
- src/pages/src/views/organization/components/collaboration-item.vue
> feat: 选中组织架构增加tenantId参数

- src/bk-login/bklogin/authentication/urls.py
- src/bk-login/bklogin/authentication/views.py
- src/bk-login/pages/src/views/components/password.vue
- src/bk-user/bkuser/apis/web/tenant_info/views.py
> fix: direct redirect c_url when user has only one account

- src/pages/src/views/tenant/OperationDetails.vue
- src/pages/src/views/tenant/index.vue
> fix: 去掉排序 && 未勾选不校验

- src/bk-login/bklogin/authentication/manager.py
- src/bk-login/bklogin/authentication/views.py
- src/bk-login/bklogin/open_apis/compatibility/views.py
> feat(login): compatibility 2.x logout

- src/bk-login/pages/src/views/home.vue
- src/pages/src/app.vue
- src/pages/src/main.ts
> feat: 组件库国际化

- src/bk-user/bkuser/apis/open_v2/mixins.py
- src/bk-user/bkuser/apis/open_v2/views/profilers.py
> feat(minor): open v2 profile api support collaboration

- src/bk-login/bklogin/authentication/urls.py
- src/bk-login/bklogin/authentication/views.py
- src/bk-login/bklogin/component/bk_user/api.py
- src/bk-login/bklogin/component/bk_user/models.py
- src/bk-user/bkuser/apis/login/serializers.py
- src/bk-user/bkuser/apis/login/urls.py
- src/bk-user/bkuser/apis/login/views.py
- src/bk-user/bkuser/common/views.py
> fix(login): forget password wrong

- src/pages/src/views/tenant/index.vue
> 修复New的Logo展示过大问题

- src/api/poetry.lock
- src/api/pyproject.toml
- src/bkuser_global/logging.py
- src/login/poetry.lock
- src/login/pyproject.toml
- src/saas/poetry.lock
- src/saas/pyproject.toml
后台（二进制部署）API日志保存不完全 https://github.com/TencentBlueKing/bk-user/issues/1477
> fix: 修复二进制日志写入异常

- src/api/bkuser_core/api/web/field/serializers.py
- src/api/bkuser_core/profiles/models.py
- src/saas/bkuser_shell/config/common/system.py
> fix：文件跳转链接调整；动态字段接口生成不可为内置字段

- src/saas/bkuser_shell/config/common/system.py
> fix:docs url load from env

- src/pages/src/router/index.js
> fix: 忘记密码页面路由修改

- src/pages/src/views/organization/components/fast-input-dialog.vue
- src/pages/src/views/organization/components/table-list.vue
- src/pages/src/views/organization/details/ViewUser.vue
- src/pages/src/views/setting/LoginSetting.vue
- src/pages/src/views/setting/auth-config/Local.vue
- src/pages/src/views/setting/auth-config/WeCom.vue
> fix；验收问题修改 

- docs/develop_guide.md
- pyproject.toml
> docs(guide): add development guide

- src/bk-user/bkuser/biz/validators.py
- src/bk-user/tests/apis/web/organization/test_user.py
- src/bk-user/tests/apis/web/personal_center/test_personal_center.py
- src/bk-user/tests/biz/test_validators.py
Fixes 后端强校验 Logo 格式，只能为 png 或 jpg
> fix: enforce logo format at submission

- src/bk-user/Dockerfile
- src/bk-user/bkuser/common/views.py
- src/bk-user/bkuser/settings.py
- src/pages/index.html
> feat(bk-user): display version info in console

- src/bk-login/bin/start.sh
- src/bk-login/bklogin/common/context_processors.py
- src/bk-login/bklogin/settings.py
- src/bk-login/bklogin/urls.py
- src/bk-login/pages/index.html
- src/bk-login/poetry.lock
- src/bk-login/pyproject.toml
- src/bk-user/bin/start.sh
- src/bk-user/bin/start_celery.sh
- src/bk-user/bin/start_celery_beat.sh
- src/bk-user/bkuser/apis/web/platform_management/views.py
- src/bk-user/bkuser/common/views.py
- src/bk-user/bkuser/settings.py
- src/pages/index.html
- 登录支持蓝鲸消息通知
- 支持虚拟账号功能页面功能开关
- 支持蓝鲸全局配置功能
- 内置租户管理员默认 Username 为 admin
- Docker 容器内进程避免 pid=1 为 bash，改进调整pid=1进程为业务实际进程
> feat(login): support bk_notice

- src/bk-user/bkuser/apis/web/organization/serializers/users.py
- src/bk-user/bkuser/apis/web/personal_center/serializers.py
- src/bk-user/bkuser/apis/web/personal_center/urls.py
- src/bk-user/bkuser/apis/web/personal_center/views.py
- src/bk-user/bkuser/apps/tenant/constants.py
- src/bk-user/bkuser/apps/tenant/models.py
- src/bk-user/bkuser/common/constants.py
- src/bk-user/tests/apis/web/organization/test_user.py
- src/bk-user/tests/apis/web/personal_center/test_personal_center.py
- src/bk-user/tests/biz/test_validators.py
> feat(bk-user): enable language and time zone setting

- .github/workflows/bk-login.yml
- .github/workflows/bk-user.yml
- .pre-commit-config.yaml
- src/bk-login/bklogin/open_apis/compatibility/mixins.py
- src/bk-login/poetry.lock
- src/bk-login/pyproject.toml
- src/bk-login/tests/authentication/test_utils.py
- src/bk-login/tests/utils/test_std_error.py
- src/bk-login/tests/utils/test_url.py
- src/bk-user/bkuser/apis/web/tenant_info/serializers.py
- src/bk-user/bkuser/apis/web/tenant_info/views.py
- src/bk-user/bkuser/apps/data_source/initializers.py
- src/bk-user/bkuser/apps/permission/permissions.py
- src/bk-user/bkuser/biz/tenant.py
- src/bk-user/bkuser/plugins/local/parser.py
- src/bk-user/poetry.lock
- src/bk-user/pyproject.toml
> feat(bk-user): only support owner tenant user setted manager

- src/bk-user/bkuser/apis/open_v2/mixins.py
- src/bk-user/bkuser/apis/open_v2/views/profilers.py
- src/bk-user/bkuser/component/http.py
> feat(open api v2): support virtual user

- src/pages/src/views/organization/index.vue
- src/pages/src/views/organization/table/PullUser.vue
- src/pages/src/views/organization/tree/TreeSearch.vue
> bug_fix:修复组织架构模块的交互问题

- src/pages/package.json
> fix: 导入文件失败，并且失败后点击详情复制提示复制失败

- src/api/poetry.lock
- src/api/pyproject.toml
- src/bkuser_global/logging.py
- src/login/poetry.lock
- src/login/pyproject.toml
- src/saas/poetry.lock
- src/saas/pyproject.toml
> fix(log): miss log when log write is file

- src/bk-user/bkuser/apis/web/organization/serializers/users.py
- src/bk-user/bkuser/apis/web/organization/views/users.py
- src/bk-user/tests/apis/web/organization/test_user.py
> feat(bk-user): enable expiration date setting in organization

- src/bk-user/bkuser/apis/web/organization/serializers/users.py
- src/bk-user/bkuser/common/constants.py
> fix(bk-user): allow fuzzy comparison between expiration dates

- src/bk-user/bkuser/apis/web/organization/serializers/__init__.py
- src/bk-user/bkuser/apis/web/organization/serializers/users.py
- src/bk-user/bkuser/apis/web/organization/urls.py
- src/bk-user/bkuser/apis/web/organization/views/__init__.py
- src/bk-user/bkuser/apis/web/organization/views/users.py
- src/bk-user/tests/apis/web/organization/test_user.py
> feat(orginization): add direct expiry date update api

- src/bk-login/bklogin/authentication/views.py
- src/bk-login/bklogin/component/bk_user/models.py
- src/bk-user/bkuser/apis/login/serializers.py
- src/bk-user/bkuser/apis/login/views.py
> feat(login): support quick login when idp is unique

- src/bk-user/bkuser/apis/open_v2/authentications.py
- src/bk-user/bkuser/apis/open_v2/views/profilers.py
- src/bk-user/bkuser/apis/web/platform_management/views.py
> fix(open api v2): jwt decode error

- src/bk-user/bkuser/common/views.py
- src/bk-user/bkuser/settings.py
- src/pages/index.html
> feat(bk-user): support enable create tenant with env variable

- src/bk-user/bkuser/apis/open_v2/urls.py
> fix(open v2 api): some without slash

- src/pages/src/views/organization/tree/OrganizationTree.vue
> fix: 修复显示问题

- src/pages/src/utils/index.ts
- src/pages/src/views/Header.vue
- src/pages/src/views/personal-center/index.vue
- src/pages/src/views/setting/LoginSetting.vue
> feat: 个人中心语言修改后，需要再触发页面语言切换

- src/bk-user/bkuser/apis/open_v2/serializers/departments.py
- src/bk-user/bkuser/apis/open_v2/views/departments.py
> fix(open api v2): department info return order field

- src/bk-user/bkuser/apis/open_v2/views/profilers.py
- src/bk-user/tests/apis/web/organization/test_user.py
- src/bk-user/tests/apis/web/personal_center/test_personal_center.py
> fix: user language unittest

- src/bk-user/bkuser/apis/web/version_log/file_extractor.py
- src/bk-user/tests/apis/web/version_log/__init__.py
- src/bk-user/tests/apis/web/version_log/test_version_log.py
> fix(locale): fixed version log language switching

- src/pages/src/components/catalog/home/ExportUser.vue
- src/pages/src/views/organization/index.vue
- src/pages/src/views/organization/tree/TreeSearch.vue
> bug_fix:修复组织架构删除用户后未重置分页，左侧异步搜索用户问题；用户目录导出时使用原生输入法搜索不到存在的数据问题

- src/bk-login/bklogin/authentication/views.py
- src/bk-login/bklogin/settings.py
- src/bk-user/bkuser/apis/open_v2/views/departments.py
- src/bk-user/bkuser/apis/open_v2/views/profilers.py
- 【OpenV2API】 兼容当用户为虚拟用户时，获取用户部门时 404
- 登录回调地址支持环境变量配置是否必须 https
> fix(open v2 api): fetch user department 404 when user is virtual user

- src/api/bkuser_core/api/web/department/serializers.py
- src/api/bkuser_core/api/web/department/views.py
> feat：部门下检索组织成员支持条件过滤

- src/pages/src/store/modules/organization.js
- src/pages/src/views/audit/index.vue
- src/pages/src/views/organization/index.vue
> fix: 修复【用户管理】组织架构搜索用户时，搜索范围不是当前目录，而是全局的问题&组织架构中仅显示本级组织成员选项，数字未及时更新问题&文案修改

- src/pages/src/views/organization/index.vue
> fix: 修复【用户管理】组织架构查询用户接口传参问题

- src/api/bkuser_core/api/web/department/serializers.py
- src/api/bkuser_core/api/web/department/views.py
> fix: 修复查询递归组织成员返回匹配本级组织成员总数

- src/pages/src/views/organization/index.vue
> fix: 修复【用户管理】组织架构在有条件查询时，勾选仅显示本级组织成员时，表格数据未更新问题

- src/bk-user/bkuser/apis/open_v1/__init__.py
- src/bk-user/bkuser/apis/open_v1/authentications.py
- src/bk-user/bkuser/apis/open_v1/mixins.py
- src/bk-user/bkuser/apis/open_v1/permissions.py
- src/bk-user/bkuser/apis/open_v1/renderers.py
- src/bk-user/bkuser/apis/open_v1/serializers.py
- src/bk-user/bkuser/apis/open_v1/urls.py
- src/bk-user/bkuser/apis/open_v1/views.py
- src/bk-user/bkuser/apis/open_v2/authentications.py
- src/bk-user/bkuser/urls.py
- src/bk-user/pyproject.toml
- src/bk-user/tests/apis/open_v1/conftest.py
- src/bk-user/tests/apis/open_v1/test_profiles.py
- 新增 Open V1 兼容 API (更新用户部分信息和批量查询用户信息)
> feat: open v1 api

- src/bk-login/bklogin/component/bk_user/api.py
- src/bk-user/bkuser/urls.py
- src/idp-plugins/idp_plugins/local/client.py
- src/pages/src/components/import-dialog/import-dialog.vue
- src/pages/src/http/api.ts
- src/pages/src/http/authSourceFiles.ts
- src/pages/src/http/dataSourceFiles.ts
- src/pages/src/http/fetch/index.ts
- src/pages/src/http/organizationFiles.ts
- src/pages/src/http/personalCenterFiles.ts
- src/pages/src/http/resetPasswordFiles.ts
- src/pages/src/http/settingFiles.ts
- src/pages/src/http/tenantsFiles.ts
- src/pages/src/http/virtualAccount.ts
- src/pages/src/views/MainHeader.vue
- src/pages/src/views/setting/data-source/ConfigList.vue
> refactor(router): modify v1 prefix to v3

- src/bk-user/bkuser/apis/web/data_source/schema.py
- src/bk-user/bkuser/apis/web/data_source/serializers.py
- src/bk-user/bkuser/apis/web/data_source/urls.py
- src/bk-user/bkuser/apis/web/data_source/views.py
- src/bk-user/bkuser/apis/web/idp/serializers.py
- src/bk-user/bkuser/apis/web/idp/urls.py
- src/bk-user/bkuser/apis/web/idp/views.py
- src/bk-user/bkuser/common/error_codes.py
- src/bk-user/tests/apis/web/data_source/test_plugin.py
Fixes #1543  自定义数据源插件配置编辑页需要支持 JsonSchema 渲染表单
> feat: added JsonSchema support for custom data source plugin configuration

- src/pages/src/views/organization/components/batch-operation.vue
- src/pages/src/views/organization/components/table-list.vue
> feat: enabled password

- src/pages/src/http/organizationFiles.ts
- src/pages/src/views/organization/components/table-list.vue
> feat:组织架构页面，只有 hover 到组织上时，才请求完整的组织路径

- src/pages/src/components/passwordInput.vue
> fix:通用 HTTP 数据源编辑，BasicAuth 模式下 Password 没有回填

- src/pages/src/views/setting/data-source/ConfigList.vue
sideSlider配置render-derctive=“if” 使syncRecord组件触发Unmount清除轮询请求
> fix: 数据源配置-数据变更记录侧边栏收起时，轮询还在触发

- src/bk-user/Dockerfile
- src/bk-user/bin/start.sh
> fix: added instruction for collecting static resources in start.sh

- src/bk-user/Dockerfile
删除 Dockerfile 中 python manage.py collectstatic 指令
> fix: delete collectstatic code in dockerfile

- src/pages/src/views/setting/data-source/NewDataSource.vue
> fix:仅custom_plugin调用jsonSchema接口

- src/api/bkuser_core/api/web/field/serializers.py
> 内置字段可被抓包修改问题

- src/pages/src/views/organization/details/UserMaterial.vue
> fix: 修复重置密码时未使用最新密码设置规则校验的问题

- src/pages/src/views/setting/data-source/NewDataSource.vue
> fix: 数据源配置兼容各类型的jsonSchema表单展示

- src/pages/src/views/setting/data-source/ConfigList.vue
> fix: 修复数据源配置下，本地数据源首次导入时，关闭dialog导致控制台报错问题

- src/pages/src/views/tenant/index.vue
> feat: 创建租户用户名统一显示admin

- src/pages/src/http/types/dataSourceFiles.ts
- src/pages/src/views/setting/data-source/ConfigList.vue
> fix: datasource close dialog

- src/pages/src/http/dataSourceFiles.ts
> fix: 移除getCustomPlugin上多余的域名

- src/pages/src/views/personal-center/verifyIdentityInfoDialog.vue
> fix: 验证码错误文案改为验证码错误，请重试

- src/pages/src/hooks/useVerifyDialog.ts
- src/pages/src/views/personal-center/EmailVerify.vue
- src/pages/src/views/personal-center/PhoneVerify.vue
- src/pages/src/views/personal-center/index.vue
- src/pages/src/views/personal-center/openDialogType.ts
> fix: 修复验证码切换弹窗，倒计时失效的问题

- src/pages/src/views/personal-center/index.vue
> fix: 修复切换Select不清除未验证的自定义数据问题

- src/bk-user/bkuser/apis/web/data_source/serializers.py
- src/bk-user/bkuser/apis/web/data_source/views.py
- src/bk-user/bkuser/biz/data_source.py
合并数据源同步任务 & 租户同步任务状态与耗时，用于前端展示
> feat: merge status and duration in data source sync task

- src/pages/src/views/setting/data-source/LdapConfig.vue
1. user_group_config修改默认参数
2. 用户组过滤器改为必填
> fix: ldap数据源配置报错

- src/pages/src/components/SyncRecords.vue
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/index.vue
> fix: 修复同步数据源耗时展示错误问题

- src/pages/src/components/SyncRecords.vue
- src/pages/src/utils/index.ts
- src/pages/src/views/setting/cross-tenant-collaboration/other-share/index.vue
> refactor: durationText

- src/bk-login/Dockerfile
- src/bk-user/Dockerfile
> fix: update python version in Dockerfile

- src/pages/src/views/organization/components/search-org.vue
- src/pages/src/views/organization/components/search-result-tree.vue
- src/pages/src/views/organization/index.vue
> fix: 重置搜索框

- src/bk-user/bkuser/apis/web/organization/views/users.py
对于租户用户的批量操作（修改用户状态 & 修改用户过期时间）支持非本地实名数据源
> feat: modify type of data source for account expired and status apis

- src/pages/src/views/organization/components/batch-operation.vue
- src/pages/src/views/organization/components/table-list.vue
> feat: ldap用户批量修改状态与续期

- src/pages/src/views/organization/components/batch-operation.vue
> fix: 批量修改字段下拉框关闭后隐藏

- src/pages/src/components/MemberSelector.vue
- src/pages/src/views/operations-history/index.vue
> feat: audit-ui

- src/pages/src/views/organization/components/batch-operation.vue
- src/pages/src/views/organization/components/table-list.vue
> feat: ldap disabled batch action

- src/bk-user/bkuser/apps/audit/constants.py
- src/bk-user/locale/en/LC_MESSAGES/django.po
- src/bk-user/locale/zh_CN/LC_MESSAGES/django.po
Nit: 调整了一些审计对象类型与审计操作行为中的枚举值表示
> style: modify some enum fields in audit

- src/pages/src/views/operations-history/index.vue
- src/pages/src/views/operations-history/operations.ts
> feat: delete virtual_user type

- src/pages/src/views/organization/components/batch-operation.vue
> style: account expiration time

- src/pages/src/views/setting/data-source/ConfigList.vue
- src/pages/src/views/setting/data-source/HttpDetails.vue
1. 数据源同步过程中禁用同步按钮
2. 本地数据源导入过程中禁用导入按钮
3. 点击LDAP数据源展示LDAP折叠信息
> fix: disable synchronization button in data source synchronization

- src/pages/src/components/MemberSelector.vue
- src/pages/src/views/operations-history/index.vue
- src/pages/src/views/operations-history/operations.ts
> feat: audit check

- src/bk-user/bkuser/apis/open_v2/serializers/profilers.py
- src/bk-user/bkuser/apis/open_v2/views/profilers.py
- src/bk-user/tests/apis/open_v2/test_profiles.py
【兼容】list_profile 接口支持 department 过滤
> feat: added filter by departments for list profiles

- src/bk-user/bkuser/apis/open_v2/views/profilers.py
修改 open_v2 中 ProfileStatusEnum 的枚举基类
> fix: modify class enum in openapi

- src/pages/src/views/operations-history/index.vue
> fix: audit table setting and table height

- src/bk-login/Dockerfile
- src/bk-login/bin/post_migrate.sh
- src/bk-login/bklogin/settings.py
- src/bk-login/support-files/apidocs/en/get_bk_token_userinfo.md
- src/bk-login/support-files/apidocs/en/verify_bk_token.md
- src/bk-login/support-files/apidocs/zh/get_bk_token_userinfo.md
- src/bk-login/support-files/apidocs/zh/verify_bk_token.md
- src/bk-login/support-files/bin/sync-apigateway.sh
- src/bk-login/support-files/definition.yaml
- src/bk-login/support-files/resources.yaml
> feat: sync openapi to apigateway automatically

- src/bk-user/bkuser/apis/apigw/__init__.py
- src/bk-user/bkuser/apis/apigw/authentications.py
- src/bk-user/bkuser/apis/apigw/permissions.py
- src/bk-user/bkuser/apis/apigw/urls.py
- src/bk-user/bkuser/apis/apigw/views.py
- src/bk-user/bkuser/settings.py
- src/bk-user/bkuser/urls.py
- src/bk-user/tests/apis/apigw/__init__.py
- src/bk-user/tests/apis/apigw/conftest.py
- src/bk-user/tests/apis/apigw/test_tenant_user.py
- [内部网关 API] 根据 bk_username 查询用户租户 ID
> feat(api): retrieve tenant user by id

- src/bk-user/bkuser/apis/open_v3/__init__.py
- src/bk-user/bkuser/apis/open_v3/mixins.py
- src/bk-user/bkuser/apis/open_v3/permissions.py
- src/bk-user/bkuser/apis/open_v3/serializers/__init__.py
- src/bk-user/bkuser/apis/open_v3/serializers/tenant.py
- src/bk-user/bkuser/apis/open_v3/urls.py
- src/bk-user/bkuser/apis/open_v3/views/__init__.py
- src/bk-user/bkuser/apis/open_v3/views/tenant.py
- src/bk-user/bkuser/settings.py
- src/bk-user/bkuser/urls.py
- src/bk-user/poetry.lock
- src/bk-user/pyproject.toml
- src/bk-user/requirements.txt
- src/bk-user/requirements_dev.txt
- src/bk-user/tests/apis/open_v3/__init__.py
- src/bk-user/tests/apis/open_v3/conftest.py
- src/bk-user/tests/apis/open_v3/test_tenant.py
> feat(open api v3): list tenant

- src/bk-user/bkuser/apis/open_v3/views/tenant.py
- src/bk-user/support-files/apidocs/en/list_tenant.md
- src/bk-user/support-files/apidocs/zh/list_tenant.md
- src/bk-user/tests/apis/open_v3/test_tenant.py
> feat: support full list tenant api

- src/bk-user/bkuser/apis/open_v3/mixins.py
- src/bk-user/bkuser/apis/open_v3/views/user.py
- src/bk-user/tests/apis/open_v3/conftest.py
[OpenAPI V3] 检查 租户级别接口，需从 Header 获取 TenantID 用于查询或校验等
> feat: get TenantID from header for OpenAPI

- src/bk-user/bkuser/apis/open_v3/serializers/department.py
- src/bk-user/bkuser/apis/open_v3/urls.py
- src/bk-user/bkuser/apis/open_v3/views/__init__.py
- src/bk-user/bkuser/apis/open_v3/views/department.py
- src/bk-user/support-files/apidocs/en/batch_query_user_display_name.md
- src/bk-user/support-files/apidocs/en/list_department.md
- src/bk-user/support-files/apidocs/en/list_department_descendant.md
- src/bk-user/support-files/apidocs/en/list_department_user.md
- src/bk-user/support-files/apidocs/en/list_tenant.md
- src/bk-user/support-files/apidocs/en/list_user.md
- src/bk-user/support-files/apidocs/en/list_user_department.md
- src/bk-user/support-files/apidocs/en/list_user_leader.md
- src/bk-user/support-files/apidocs/en/retrieve_department.md
- src/bk-user/support-files/apidocs/en/retrieve_user.md
- src/bk-user/support-files/apidocs/zh/batch_query_user_display_name.md
- src/bk-user/support-files/apidocs/zh/list_department.md
- src/bk-user/support-files/apidocs/zh/list_department_descendant.md
- src/bk-user/support-files/apidocs/zh/list_department_user.md
- src/bk-user/support-files/apidocs/zh/list_tenant.md
- src/bk-user/support-files/apidocs/zh/list_user.md
- src/bk-user/support-files/apidocs/zh/list_user_department.md
- src/bk-user/support-files/apidocs/zh/list_user_leader.md
- src/bk-user/support-files/apidocs/zh/retrieve_department.md
- src/bk-user/support-files/apidocs/zh/retrieve_user.md
- src/bk-user/support-files/resources.yaml
- src/bk-user/tests/apis/open_v3/test_department.py
[OpenAPI V3] 分页 API  - 根据 部门 ID 查询用户列表
> feat: added query department user list

- src/pages/src/components/notify-editor/NotifyEditorTemplate.vue
- src/pages/src/views/organization/components/batch-operation.vue
- src/pages/src/views/organization/components/batch-renewal.vue
> feat: batch renewal

- src/pages/src/components/SyncRecords.vue
- src/pages/src/http/dataSourceFiles.ts
- src/pages/src/http/types/dataSourceFiles.ts
> fix: sideslide stop time polling while sync status done

- src/bk-user/bkuser/apis/web/organization/views/users.py
> fix: fixed batch create user bug

- src/bk-user/bkuser/common/views.py
> feat: added vue template for apigw url

- src/bk-user/support-files/bk-user-apigateway/resources.yaml
- src/bk-user/support-files/bk-user-web-apigateway/resources.yaml
> feat: added apply open api permission

- src/bk-login/bklogin/authentication/views.py
- src/bk-login/bklogin/component/bk_user/constants.py
- src/bk-login/bklogin/component/bk_user/models.py
- src/bk-login/bklogin/open_apis/urls.py
- src/bk-login/bklogin/open_apis/views.py
- src/bk-login/bklogin/settings.py
- src/bk-login/tests/open_apis/test_bk_token.py
- src/bk-user/bkuser/apis/apigw/urls.py
- src/bk-user/bkuser/apis/apigw/views.py
- src/bk-user/bkuser/apis/login/serializers.py
- src/bk-user/bkuser/apps/tenant/constants.py
- src/bk-user/bkuser/apps/tenant/management/commands/create_tenant.py
- src/bk-user/bkuser/apps/tenant/migrations/0003_init_default_tenant.py
- src/bk-user/bkuser/settings.py
- src/bk-user/tests/apis/apigw/test_tenant_user.py
- 支持创建租户的 Django CMD
- 添加内置管理员账号仅在用户管理内使用的限制
- 优化 bk-user 网关 API 代码
> feat(django cmd): create tenant

- src/bk-user/support-files/bin/sync-bk-user-apigateway.sh
- src/bk-user/support-files/bk-user-apigateway/definition.yaml
> feat: added grant permissions for app

- src/bk-user/bkuser/apis/open_v3/serializers/user.py
- src/bk-user/support-files/bk-user-apigateway/apidocs/en/list_user_sensitive_info.md
- src/bk-user/support-files/bk-user-apigateway/apidocs/zh/list_user_sensitive_info.md
- src/bk-user/tests/apis/open_v3/test_user.py
> feat: added the WeChat ID field to the output of user sensitive information api

- src/bk-user/bkuser/apis/web/platform_management/serializers.py
- src/bk-user/bkuser/apps/tenant/constants.py
- src/bk-user/bkuser/apps/tenant/management/commands/create_tenant.py
- src/bk-user/locale/en/LC_MESSAGES/django.po
- src/bk-user/locale/zh_CN/LC_MESSAGES/django.po
> feat: modify tenant id regex

- src/bk-user/bkuser/apis/apigw/mixins.py
- src/bk-user/bkuser/apis/open_v3/mixins.py
- src/bk-user/locale/en/LC_MESSAGES/django.po
- src/bk-user/locale/zh_CN/LC_MESSAGES/django.po
> style: modify error message for openapi

- src/bk-user/support-files/bk-user-web-apigateway/resources.yaml
更改 update_current_user_language 接口的前端请求方法
> fix: modify method type for openapi

- src/bk-user/bkuser/biz/validators.py
- src/bk-user/bkuser/plugins/local/constants.py
- src/bk-user/bkuser/plugins/local/parser.py
- src/bk-user/locale/en/LC_MESSAGES/django.po
- src/bk-user/locale/zh_CN/LC_MESSAGES/django.po
> feat: modify regex for username

- src/bk-user/support-files/bk-user-web-apigateway/definition.yaml
OpenAPI 网关跨域请求允许携带 header 头 Content-Type
> feat: added allow origin header for openapi

- src/pages/src/utils/index.ts
- src/pages/src/views/MainHeader.vue
- src/pages/src/views/personal-center/index.vue
> feat: update toggle language interface

- src/bk-user/bkuser/apps/tenant/management/commands/tenant_common_variable.py
> fix: modify output of tenant common variable command

- src/bk-user/support-files/bk-user-web-apigateway/apidocs/zh/batch_lookup_user.md
> docs: modify word for apidocs

- src/pages/src/views/organization/components/fast-input-dialog.vue
> feat: 快速录入table支持动态field渲染，confirm增加loading

- src/bk-user/bkuser/apis/web/audit/serializers.py
- src/bk-user/bkuser/common/views.py
- src/bk-user/support-files/bk-user-apigateway/definition.yaml
- src/bk-user/support-files/bk-user-web-apigateway/definition.yaml
- src/bk-user/tests/apis/web/audit/test_audit.py
删去代码中测试 display_name 展示组件时所添加内容
> fix: modify creator display_name for audit record

- src/bk-user/bkuser/apis/open_v3/serializers/relation.py
- src/bk-user/bkuser/apis/open_v3/urls.py
- src/bk-user/bkuser/apis/open_v3/views/__init__.py
- src/bk-user/bkuser/apis/open_v3/views/relation.py
- src/bk-user/support-files/bk-user-apigateway/apidocs/en/list_department_user_relation.md
- src/bk-user/support-files/bk-user-apigateway/apidocs/zh/list_department_user_relation.md
- src/bk-user/support-files/bk-user-apigateway/definition.yaml
- src/bk-user/support-files/bk-user-apigateway/resources.yaml
- src/bk-user/tests/apis/open_v3/test_relation.py
> feat: added query department user relation for openapi

- src/pages/src/components/passwordInput.vue
- src/pages/src/views/organization/components/batch-operation.vue
- src/pages/src/views/organization/components/table-list.vue
> fix: 切换pageSize表头消失、批量重置loading

- src/bk-user/bkuser/apis/web/organization/serializers/users.py
- src/bk-user/tests/apis/web/organization/conftest.py
- src/bk-user/tests/apis/web/organization/test_user.py
- src/bk-user/tests/test_utils/data_source.py
> fix: added password expiration time

- src/pages/src/components/import-dialog/import-dialog.vue
- src/pages/src/hooks/useDataSource.ts
- src/pages/src/views/organization/components/batch-operation.vue
- src/pages/src/views/organization/components/fast-input-dialog.vue
- src/pages/src/views/organization/components/table-list.vue
> fix: 优化导入数据提示 & 优化重置密码loading

- src/bk-user/bkuser/apis/open_v3/serializers/relation.py
- src/bk-user/bkuser/apis/open_v3/urls.py
- src/bk-user/bkuser/apis/open_v3/views/__init__.py
- src/bk-user/bkuser/apis/open_v3/views/relation.py
- src/bk-user/support-files/bk-user-apigateway/apidocs/en/list_user_leader_relation.md
- src/bk-user/support-files/bk-user-apigateway/apidocs/zh/list_user_leader_relation.md
- src/bk-user/support-files/bk-user-apigateway/resources.yaml
- src/bk-user/tests/apis/open_v3/test_relation.py
> feat: added query user leader relation for openapi

- src/pages/src/components/SyncRecords.vue
> fix: sync filter

- src/pages/src/views/MainHeader.vue
> fix: 根据当前语言状态跳转文档

- src/pages/src/views/organization/components/table-list.vue
> fix: page size change scroll uninit

- src/api/bkuser_core/categories/plugins/utils.py
- src/api/bkuser_core/common/db_sync.py
- src/api/bkuser_core/config/common/storage.py
- src/bkuser_global/config.py
- src/saas/Dockerfile
修复
1、缺陷/用户管理ldap目录拉取周期修改不生效 #2113
2、用户管理ldap同步批量插入失败后使用单个插入，报事务冲突 #2112
新增
3、用户管理tls/ssl单向和双向客户端&服务段加密 #2111
> Dev/2.5.3/2.5.3 beta.25 ssl.2

- src/bk-user/bkuser/apps/tenant/constants.py
- src/bk-user/bkuser/apps/tenant/display_name_cache.py
- src/bk-user/bkuser/biz/tenant.py
- src/bk-user/tests/apis/open_web/conftest.py
- src/bk-user/tests/apis/open_web/test_user.py
> refactor: optimize custom expression for display_name

- src/pages/src/components/user-display-name-config/userDisplayNameConfig.vue
> feat: filter enum display name options

- src/bk-user/bkuser/apps/tenant/display_name_cache.py
- src/bk-user/bkuser/biz/tenant.py
> refactor:modify render display_name expression

- src/bk-login/pages/src/views/home.vue
> fix: 无租户时不调用接口

- src/bk-login/bklogin/authentication/urls.py
- src/bk-login/bklogin/authentication/views.py
> feat: opt login

- src/bk-user/bkuser/apis/web/personal_center/views.py
修复用户没有设置自定义枚举字段时，个人中心报错 500 的问题
> fix: modify personal center custom field display

- docs/develop_guide.md
修复开发文档中的路径错误(bk-login -> bk-user)
> fix(develop_guide.md): Correct typo in develop_guide.md(bk-login -> bk-user)

- src/bk-user/bkuser/apis/web/virtual_user/serializers.py
- src/bk-user/bkuser/apis/web/virtual_user/views.py
- src/bk-user/locale/en/LC_MESSAGES/django.po
- src/bk-user/locale/zh_CN/LC_MESSAGES/django.po
- src/bk-user/tests/apis/web/organization/test_user.py
- src/bk-user/tests/apis/web/virtual_user/__init__.py
- src/bk-user/tests/apis/web/virtual_user/conftest.py
- src/bk-user/tests/apis/web/virtual_user/test_virtual_user.py
> feat(virtual_user): enhance virtual user api

- src/saas/bkuser_shell/config/overlays/prod.py
> bugfix: saas https csrf

- src/bk-user/bkuser/apis/open_v3/mixins.py
- src/bk-user/bkuser/apis/open_v3/views/user.py
- src/bk-user/bkuser/apis/open_web/mixins.py
- src/bk-user/bkuser/apis/open_web/views/users.py
添加 “根据 login_name  查询虚拟用户 bk_username” OpenAPI 接口过滤条件（数据源类型为 DataSourceTypeEnum.VIRTUAL)
> fix: added filter condition for virtual user query OpenAPI

- src/bk-user/bkuser/apps/tenant/display_name_cache.py
修改 display_name 自定义表达式配置缓存时间为 1 min
> feat: modify display name config cache time

- src/bk-user/bkuser/apis/web/organization/views/users.py
- src/bk-user/bkuser/apis/web/virtual_user/views.py
- src/bk-user/bkuser/biz/auditor.py
> feat: modify virtual user audit

- src/bk-login/pages/src/views/home.vue
> feat: 登录 loading 优化

- src/pages/src/views/setting/index.vue
> fix: enable collaboration tenant
