src/api/bkuser_core/common/viewset.py, src/api/bkuser_core/tests/apis/profiles/test_profiles_list.py, src/saas/bkuser_shell/organization/serializers/profiles.py, src/saas/bkuser_shell/organization/views/misc.py, src/saas/bkuser_shell/organization/views/profiles.py
- 调整 SaaS 获取用户 API `categories/${id}/profiles/` 逻辑，去除全量参数，支持参数搜索
- 修复搜索 API 异常（后端去除全量导致）
- API 部分调整，支持 `wildcard` 和 `lookup` 搜索同时工作
Fixes #55
=> fix #55: SaaS 获取用户 API 调整，修复搜索 API 异常等

src/api/bkuser_core/audit/constants.py, src/api/bkuser_core/categories/models.py, src/api/bkuser_core/categories/urls.py, src/api/bkuser_core/common/error_codes.py, src/api/bkuser_core/common/models.py, src/api/bkuser_core/common/viewset.py, src/api/bkuser_core/departments/models.py, src/api/bkuser_core/departments/urls.py, src/api/bkuser_core/profiles/models.py, src/api/bkuser_core/profiles/urls.py, src/api/bkuser_core/tests/apis/categories/test_categories.py, src/api/bkuser_core/tests/apis/departments/test_departments.py, src/api/bkuser_core/tests/apis/profiles/test_profiles_action.py, src/api/bkuser_core/tests/utils.py
Fix issue15: https://github.com/TencentBlueKing/bk-user/issues/15 
Signed-off-by: Chenyang Yan <memory.yancy@gmail.com>
=> Fix issue15 -- support restoration soft delete object data

deploy/helm/bk-user-stack/values.yaml, deploy/helm/saas/values.yaml, src/api/bkuser_core/categories/handlers.py, src/api/bkuser_core/config/common/platform.py, src/saas/bkuser_shell/common/viewset.py, src/saas/bkuser_shell/config/common/platform.py
=> fix: 调整 IAM 启停环境变量，统一 SaaS & Api; 当主动关闭权限中心时，跳过目录新建关联权限

src/api/bkuser_core/common/exception_handler.py
=> fix(logging/exception): remove redundant logging while handle the exceptions

deploy/helm/bk-user/charts/api/templates/web-deployment.yaml
```
[25/Feb/2022:14:30:32 +0800] "GET /ping HTTP/1.1" 301 1772 0 "-" "kube-probe/1.21"
[25/Feb/2022:14:30:32 +0800] "GET /ping HTTP/1.1" 301 1772 0 "-" "kube-probe/1.21"
[25/Feb/2022:14:30:32 +0800] "GET /ping/ HTTP/1.1" 200 1954 4 "http://10.244.0.5:8000/ping" "kube-probe/1.21"
[25/Feb/2022:14:30:32 +0800] "GET /ping/ HTTP/1.1" 200 2666 4 "http://10.244.0.5:8000/ping" "kube-probe/1.21"
```
=> fix(deploy/helm): fix /ping always redirect to /ping/ in kube-probe

deploy/helm/bk-user/Chart.yaml, deploy/helm/bk-user/charts/api/Chart.yaml, deploy/helm/bk-user/charts/api/values.yaml, deploy/helm/bk-user/charts/login/Chart.yaml, deploy/helm/bk-user/charts/login/values.yaml, deploy/helm/bk-user/charts/saas/Chart.yaml, deploy/helm/bk-user/charts/saas/values.yaml, src/api/bkuser_core/audit/utils.py, src/api/bkuser_core/common/exception_handler.py, src/api/bkuser_core/config/overlays/unittest.py, src/api/bkuser_core/profiles/password.py, src/bkuser_global/logging.py, src/saas/bkuser_shell/apis/viewset.py
- bugfix: 打印双份日志问题
- saas调用后台报错打印详细信息
- saas调用API增加request_id
- 审计中记录调用来源 `bk_app_code`
=> feat(api/logging): enhance the logging while api 500

src/api/bkuser_core/categories/management/commands/make_crontab_sync_task_for_category.py, src/api/bkuser_core/categories/plugins/custom/models.py, src/api/bkuser_core/categories/plugins/plugin.py, src/api/bkuser_core/categories/tasks.py, src/api/bkuser_core/config/common/system.py, src/api/bkuser_core/departments/v2/serializers.py, src/api/bkuser_core/departments/v2/views.py, src/api/bkuser_core/profiles/v2/serializers.py, src/api/bkuser_core/profiles/v2/views.py, src/api/bkuser_core/tests/categories/plugins/custom/test_client.py, src/saas/bkuser_shell/config_center/views.py
=> fix(api/category): fix http api datasource syncer

src/api/bkuser_core/categories/plugins/custom/client.py
- 检查: http接口作为数据源时, 检查获取到的数据(避免在后面处理时报错无法感知原因)
=> fix(plugin/custom): fix http api as datasource wrong response check

src/api/bkuser_core/enhanced_account/authentication.py
=> fix(api/enhanced_account): token auth fail with different exception message

.github/workflows/unittest.yml, deploy/helm/bk-user/charts/api/templates/external-storage-configmap.yaml, deploy/helm/bk-user/templates/redis-env-configmap.yaml, src/api/bkuser_core/categories/plugins/custom/helpers.py, src/api/bkuser_core/categories/plugins/ldap/client.py, src/api/bkuser_core/categories/plugins/ldap/handlers.py, src/api/bkuser_core/config/common/.env-tmpl, src/api/bkuser_core/config/common/django_basic.py, src/api/bkuser_core/config/common/storage.py, src/api/bkuser_core/config/overlays/unittest.py, src/api/poetry.lock, src/api/pyproject.toml
=> fix(api/celery): change CELERY_RESULT_BACKEND to django-db, instead of MQ or Redis

src/api/bkuser_core/profiles/v2/views.py
=> fix(api/profile): leader has no domain in username

deploy/helm/bk-user/charts/login/templates/general-envs-configmap.yaml, deploy/helm/bk-user/charts/login/values.yaml, deploy/helm/bk-user/values.yaml, src/bkuser_global/crypt.py, src/login/bklogin/bkauth/forms.py, src/login/bklogin/common/context_processors.py, src/login/bklogin/config/common/django_basic.py, src/login/bklogin/templates/account/login.html, src/login/bklogin/templates/account/login_ce.html, src/login/poetry.lock, src/login/pyproject.toml, src/login/static/assets/jsencrypt-3.2.1.min.js
=> feature: 登录时，支持密码明文进行加密处理

src/api/bkuser_core/common/middlewares.py, src/saas/bkuser_shell/proxy/proxy.py
bugfix:
- api: ee response存在缓存导致的数据结构错误
- saas: proxy response中encoding错误
=> fix(responseandproxy): force_ee_response & proxy response headers bug

src/api/bkuser_core/api/web/category/views.py, src/api/bkuser_core/categories/plugins/ldap/handlers.py
#777
原因: 首次创建目录的时候, 目录配置还没被初始化, 此时config_provider是拿不到任何东西的; 默认是None
=> fix(ldap/create): create mad dir fail while update_or_create_sync_tasks

src/api/bkuser_core/api/web/category/serializers.py, src/api/bkuser_core/api/web/category/views.py, src/api/bkuser_core/categories/plugins/local/syncer.py, src/api/bkuser_core/tests/categories/plugins/local/test_syncer.py
- 功能点：本地目录通过excel导入用户，支持可选的更新参数：如果用户勾选以更新方式导入，用户部门变更不会以新增方式处理，会直接更新用户的部门信息；
- 相关issue：https://github.com/TencentBlueKing/bk-user/issues/728
=> feat: 本地目录导入excel支持选择更新 #728

src/api/bkuser_core/api/web/category/serializers.py, src/api/bkuser_core/api/web/category/views.py, src/api/bkuser_core/api/web/constants.py, src/api/bkuser_core/api/web/password/serializers.py, src/api/bkuser_core/api/web/password/urls.py, src/api/bkuser_core/api/web/password/views.py, src/api/bkuser_core/api/web/profile/serializers.py, src/api/bkuser_core/api/web/utils.py, src/api/bkuser_core/categories/management/commands/enable_pwd_rsa_encrypt.py, src/api/bkuser_core/user_settings/migrations/0019_alter_local_password_rsa_config.py, src/api/poetry.lock, src/api/pyproject.toml
1. SettingMeta 新增rsa元数据
2. 通过命令Django Command 针对某个目录进行启用rsa加密，并且秘钥对具有差异化（支持随机生成秘钥对，本地pem文件导入）
=> feature: 页面操作密码重置，rsa加密

src/api/bkuser_core/api/web/constants.py, src/api/bkuser_core/api/web/setting/views.py
meta接口发挥rsa的meta数据；创建目录时，生成rsa的默认配置，导致后续校验失败
=> fix: 目录meta list接口rsa设置不返回

src/pages/src/views/setting/AccountSetting.vue
=> fix: 账号有效期交互优化

.github/workflows/bk-login.yml, .github/workflows/bk-user.yml, .github/workflows/idp-plugins.yml, .pre-commit-config.yaml, src/bk-login/pyproject.toml, src/bk-user/bkuser/apis/login/serializers.py, src/bk-user/bkuser/apis/login/views.py, src/bk-user/bkuser/apis/web/idp/__init__.py, src/bk-user/bkuser/apis/web/idp/serializers.py, src/bk-user/bkuser/apis/web/idp/swagger.py, src/bk-user/bkuser/apis/web/idp/urls.py, src/bk-user/bkuser/apis/web/idp/views.py, src/bk-user/bkuser/apis/web/urls.py, src/bk-user/bkuser/apps/idp/handlers.py, src/bk-user/bkuser/apps/idp/models.py, src/bk-user/bkuser/apps/permission/permissions.py, src/bk-user/bkuser/common/constants.py, src/bk-user/bkuser/common/error_codes.py, src/bk-user/pyproject.toml, src/bk-user/tests/apis/web/idp/__init__.py, src/bk-user/tests/apis/web/idp/test_idp.py, src/bk-user/tests/test_utils/__init__.py, src/bk-user/tests/test_utils/auth.py, src/bk-user/tests/test_utils/data_source.py, src/bk-user/tests/test_utils/natural_user.py, src/idp-plugins/idp_plugins/base.py, src/idp-plugins/pyproject.toml
=> feat(bkuser): idp cur api

src/bk-user/bkuser/biz/idp.py, src/bk-user/tests/biz/test_idp.py
=> fix: auth tenant user not match `id` field

src/bk-login/pages/src/views/components/password.vue, src/bk-login/pages/src/views/home.vue
=> fix: 列表选中展示字段

src/api/bkuser_core/api/login/views.py, src/api/bkuser_core/api/web/category/serializers.py, src/api/bkuser_core/api/web/export.py, src/api/bkuser_core/api/web/profile/views.py, src/api/bkuser_core/categories/plugins/local/parsers.py, src/api/bkuser_core/categories/plugins/local/syncer.py, src/api/bkuser_core/categories/plugins/plugin.py, src/api/bkuser_core/common/middlewares.py, src/api/bkuser_core/profiles/v2/serializers.py, src/api/bkuser_core/tests/categories/plugins/local/test_parsers.py, src/api/bkuser_core/tests/categories/plugins/local/test_syncer.py, src/api/bkuser_core/tests/categories/plugins/test_plugin.py
Fixes 2.5.3 bug遗留
1. login.upsert接口缺少审计
2. 未配置mad和ldap类型的目录，过几分钟后刷新页面，【未完成】标识丢失
3. 本地目录用户excel导入，未对内置字段做校验
4. mad/ldap启用状态变更，周期同步任务状态未变更
=> Fix 2.5.3 bug

src/bk-user/bkuser/apis/web/data_source_organization/serializers.py, src/bk-user/bkuser/apis/web/personal_center/serializers.py, src/bk-user/bkuser/apis/web/tenant/serializers.py, src/bk-user/bkuser/biz/validators.py, src/bk-user/bkuser/settings.py
=> feat: 限制 Logo 文件尺寸大小

src/bk-user/bkuser/apis/web/data_source/serializers.py, src/bk-user/bkuser/apis/web/data_source_organization/views.py, src/bk-user/bkuser/apis/web/password/views.py, src/bk-user/bkuser/apis/web/personal_center/views.py, src/bk-user/bkuser/apis/web/platform_management/views.py, src/bk-user/bkuser/apis/web/tenant_info/serializers.py, src/bk-user/bkuser/apis/web/tenant_info/views.py, src/bk-user/bkuser/apis/web/virtual_user/mixins.py, src/bk-user/bkuser/apps/data_source/initializers.py, src/bk-user/bkuser/apps/idp/handlers.py, src/bk-user/bkuser/apps/notification/tasks.py, src/bk-user/bkuser/apps/sync/handlers.py, src/bk-user/bkuser/plugins/local/defaults.py, src/bk-user/bkuser/plugins/local/models.py, src/bk-user/tests/apis/web/data_source/test_data_source.py, src/bk-user/tests/apis/web/personal_center/test_personal_center.py, src/bk-user/tests/apps/data_source/test_initializers.py, src/bk-user/tests/apps/data_source/test_models.py, src/bk-user/tests/fixtures/data_source.py, src/idp-plugins/idp_plugins/local/plugin.py, src/pages/src/hooks/useDataSource.ts, src/pages/src/http/types/settingFiles.ts, src/pages/src/views/data-source/local-details/PswInfo.vue, src/pages/src/views/data-source/local-details/index.vue, src/pages/src/views/data-source/new-data/Local.vue, src/pages/src/views/setting/AdminSetting.vue
=> feat(bkuser): adjust local data source config model

src/api/bkuser_core/api/login/views.py, src/api/bkuser_core/api/web/password/views.py, src/api/bkuser_core/api/web/profile/views.py
fix：parse_username_domain 解析异常，报错信息泄漏，泄漏代码绝对路径
=> fix：parse_username_domain 解析异常，报错信息泄漏，泄漏代码绝对路径

src/api/resources/apigateway/bk_apigw_resources_bk-user.yaml, src/api/resources/apigateway/definition.yaml, src/login/bklogin/templates/login.html, src/login/locale/en/LC_MESSAGES/django.po, src/login/locale/zh_Hans/LC_MESSAGES/django.po, src/saas/bkuser_shell/common/context_processors.py, src/saas/locale/en/LC_MESSAGES/django.po, src/saas/locale/zh_Hans/LC_MESSAGES/django.po
=> fix(i18n): update some trans

src/api/bkuser_core/api/web/password/serializers.py, src/api/bkuser_core/api/web/password/verification_code_handler.py, src/api/bkuser_core/api/web/password/views.py, src/api/bkuser_core/config/common/django_basic.py, src/pages/src/views/password/Sms.vue
=> fix: 修复忘记密码，用户名爆破安全漏洞

src/pages/src/views/organization/components/batch-operation.vue, src/pages/src/views/organization/components/table-list.vue
1. 移动 、重置密码、删除 仅仅在本地数据源时起效，其他数据源类型都是禁用的
2. 修改用户信息，弹框，在数据源非本地时，仅仅可以修改有效期，其他都是不允许 # Reviewed, transaction id: 17207
=> fix:组织架构 - 用户批量操作 部分操作仅本地数据源

src/bk-user/Dockerfile
添加 Dockerfile 中的指令，避免找不到 swagger 的静态资源，从而导致 swagger 页面无法渲染的问题
=> fix: added instruction for collecting static resources in Dockerfile

src/pages/src/hooks/useDataSource.ts, src/pages/src/store/syncStatus.ts, src/pages/src/utils/index.ts, src/pages/src/views/organization/components/table-list.vue, src/pages/src/views/setting/data-source/ConfigList.vue, src/pages/src/views/setting/data-source/ConfigSuccess.vue
1. 同步状态轮询请求统一改为5秒一次
2. 复组织管理因高度塌缩不显示loading
3. 重置按钮及重置过程新增loading
4. 执行中状态展示为同步中
5. 同步数据源时，重置button变为disabled状态
6. 载入或刷新页面时，对未同步状态的数据源建立轮询请求
=> feat: 数据源配置loading

src/bk-user/bkuser/apis/web/data_source/views.py, src/bk-user/bkuser/apis/web/organization/views/relations.py, src/bk-user/bkuser/apis/web/organization/views/users.py, src/bk-user/bkuser/apps/audit/constants.py, src/bk-user/bkuser/apps/audit/recorder.py, src/bk-user/bkuser/biz/auditor.py, src/bk-user/bkuser/utils/django.py
=> feat: added operation audit for data source and users

src/bk-user/Makefile, src/bk-user/locale/en/LC_MESSAGES/django.po, src/bk-user/locale/zh_CN/LC_MESSAGES/django.po
Django 版本升级后，运行 python manage.py makemessages -d django -l zh_cn -e html,part -e py 时，会出现：
**invalid locale zh_cn, did you mean zh_CN?**
通过查看源码发现 Django 对于 locale 的是否有效的判断规则发生了变化：
升级前：
升级后：
因此 zh_cn 需要更正为 zh_CN，于是将 makefile 中的命令做了更改。
=> feat: adjust locale from zh_cn to zh_CN

src/pages/src/views/operations-history/index.vue
1. page切换时，不应该同步未查询的参数
2. 限制table最大高度
3. 优化操作对象与操作类型交互
3.1. 选择操作类型时，自动同步对应的操作对象
3.2. 选择操作对象时，自动过滤操作类型的下拉选项
3.3. 选择操作类型，自动同步操作对象后，清空操作对象数据，操作对象的下拉选项不变
3.4. 选择操作对象，自动过滤操作类型后，清空操作类型数据，操作对象的下拉选项允许展示所有，但操作类型数据下拉选项依旧基于操作对象进行过滤，更加合理
3.5. 清空操作类型、操作对象两项，两者下拉框重置过滤，展示所有
3.6. 由onChange处理操作对象、操作类型改为watch监听，兼容重置按钮，不耽误操作对象、操作类型的选项过滤
=> fix: page切换时，不应该同步未查询的参数

src/bk-user/bkuser/apis/open_v3/mixins.py, src/bk-user/bkuser/apis/open_v3/pagination.py, src/bk-user/bkuser/apis/open_v3/views/department.py, src/bk-user/bkuser/apis/open_v3/views/user.py
OpenAPI 一些通用问题优化：
1. 只允许查询 实名数据源 相关数据，虚拟和内置管理数据源都不允许返回（无论是用户还是部门，只查询实名数据源的数据）
2. TenantUserListApi 分页问题，不能直接修改类属性，会影响其他接口的分页
=> fix: apis of tenant only support real data source
